[server]
# IP of host machine, because localhost is not
# visible from Docker container
Host="10.51.0.184"
Port=8084

[consul]
hostport="127.0.0.1:8500"
ttl="5s"
servicename="TrackingService"

[storage]
host="127.0.0.1"
port=9042
keyspace="tracking"
